spring:
  application:
    name: ctc-manager
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

# Statische Seitengenerierung
ctc:
  site:
    output-dir: ${user.home}/ctc-site-output
