package org.ctc.discord.model;

public enum DiscordPostType {
	TEAM_CARDS,
	SETTINGS,
	LINEUPS,
	SCHEDULE,
	PROVISIONAL_SCORES,
	MATCH_RESULTS,
	RACE_RESULTS,
	MATCHDAY_PAIRINGS,
	MATCHDAY_SCHEDULE,
	MATCH_PREVIEW,
	MATCHDAY_OVERVIEW,
	POWER_RANKINGS,
	STANDINGS
}
