ALTER TABLE seasons ADD COLUMN format VARCHAR(10) DEFAULT 'LEAGUE' NOT NULL;
ALTER TABLE seasons ADD COLUMN total_rounds INT;

ALTER TABLE races ADD COLUMN bye BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE races ALTER COLUMN away_team_id UUID NULL;
